name: test

on:
  push:
    branches:
      - ma ster

env:
    UNITTESTING_TAG: master

jobs:
  Unittesting:
    strategy:
      fail-fast: false
      matrix:
        st-version: [4]
        os: ["ubuntu-latest", "macOS-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - if: ${{ matrix.os == 'macOS-latest' }}
        run: brew unlink openssl
      - uses: SublimeText/UnitTesting/actions/setup@v1
        with:
          sublime-text-version: ${{ matrix.st-version }}
      - uses: SublimeText/UnitTesting/actions/run-tests@v1
        with:
          coverage: true
          codecov-upload: true

 Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.3'
      - run: sudo apt update
      - run: sudo apt install --no-install-recommends -y x11-xserver-utils
      - run: pip3 install flake8==5.0.4 --user
      - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - run: flake8